# Generated by Django 4.1.3 on 2023-06-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
